### PR TITLE
Feature Static Wall

### PR DESCRIPTION
**Pull request by beerhond**
- Added a wall. 
- Added futuristic ground texture.

### CODE REVIEW

**Comment by Athosvk** [comment]
Let's discuss this later. As for now, it is not conform the coding guidelines

**Comment by Athosvk** [comment]
Looks good. Would be nice if you could remove the unused include of irrlicht.h in the cpp file. However, are you sure it's all cleaned up after the wall gets destroyed? If things are already being destroyed, leave out the destructor. As I commented above, should the ground mesh/texture really be in this? Can you also ensure that the entire feature is finished before we merge it?

**Comment by Athosvk** [comment]
And fix merge conflicts

**Comment by beerhond** [comment]
You are right, textures should be in a different branch. The walls don't have collision yet. I didn't implement collision because we didn't have a player yet. I will add this now and test it.

**Pull request merged**
